languageCode = "de"
languageName = "Deutsch"
weight = 1
title = ""

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "2. January 2006"
  # logo = "img/stylite_logo.png"
  description = "ZFS, security und Docker solutions"

[params.author]
  name = "Stylite AG"
  email = "office@stylite.de"
  # image = "img/stylite_logo.png"
  headline = "ZFS, security, Docker Solutions"
  bio = "Spezialisten in ZFS storage solutions, security. Docker containerization for enterprise environments."
  links = [
    { github = "https://github.com/styliteag" },
    { globe = "https://blog.stylite.de" },
  ]